spring:
  redis:
    host: 10.17.156.10
    port: 6379
    password: k0Rquy6Sc
    database: 0           #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 5000         #连接超时时间(ms)
    lettuce:
      pool:
        max-active: 100       #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 10          #连接池中的最大空闲连接 默认 8
        min-idle: 2           #连接池中的最小空闲连接 默认 0
        max-wait: 5000        #连接池最大阻塞等待时间(ms)(负数表示无限制)
